baseURL = 'https://www.esekyi.com/'
languageCode = 'en-us'
title = 'EKS'

theme = "hugo-distill"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  description = "Your site description"
  author = "Emmanuel Sekyi"

[params.social]
  twitter = "thesekyi"
  linkedin = "in/thesekyi"
  github = "theSekyi"