[build]
  publish = "public"
  command = "hugo --config hugo.toml"

[build.environment]
  HUGO_VERSION = "0.140.2"

[context.production.environment]
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

[context.deploy-preview]
  command = "hugo --config hugo.toml -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
  command = "hugo --config hugo.toml -b $DEPLOY_PRIME_URL"