[build]
  publish = "public"
  command = "hugo --gc --minify -b $URL"

[build.environment]
  HUGO_VERSION = "0.140.2"
  HUGO_ENABLEGITINFO = "true"
  HUGO_ENV = "production"

[context.production]
  command = "hugo --gc --minify -b $URL"

[context.development]
  command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

[context.deploy-preview]
  command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"